config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'home#index'
  get '/search', to: 'book_discussions#search'
  get '/search_discussions', to: 'book_discussions#search_discussions'
  get '/invite', to: 'book_discussions#invite'
  get '/all', to: 'book_discussions#all'
  get '/status', to: 'book_discussions#change_status'
  get '/save', to: 'book_discussions#save'
  get '/remove_saved', to: 'book_discussions#remove_saved'

  resources :book_discussions
  resources :sections
  resources :comments

  get '*unmatched_route', to: 'application#not_found'

  default_url_options :host => "localhost:3000"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_discussion.rb
class BookDiscussion < ApplicationRecord
  validates :user_id, presence: true
  validates :book_title, presence: true
  validates :book_image_url, presence: true
  validates :book_author, presence: true
  validates :status, presence: true

  has_many :sections, dependent: :destroy
  belongs_to :user
end

app/models/section.rb
class Section < ApplicationRecord
  validates :book_discussion_id, presence: true
  validates :title, presence: true

  belongs_to :book_discussion
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :first_name, presence: true
  validates :last_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :book_discussions

  def self.find_first_by_auth_conditions warden_conditions
    conditions = warden_conditions.dup
    if (email = conditions.delete(:email)).present?
      where(email: email.downcase).first
    elsif conditions.has_key?(:reset_password_token)
      where(reset_password_token: conditions[:reset_password_token]).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def not_found
    redirect_to '/404'
  end

  def after_sign_in_path_for(resource)
    book_discussions_path
  end
end

app/controllers/book_discussions_controller.rb
class BookDiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_discussion, only: [:show, :destroy, :invite, :change_status, :save, :remove_saved]

  def index
    @book_discussions = []
    BookDiscussion.find_each do |discussion|
      if discussion.discussion_participants.include?(current_user.email)
        @book_discussions << discussion
      end
    end
    @saved_discussions = []
    BookDiscussion.find_each do |discussion|
      if current_user.saved_discussions.include?(discussion.id)
        @saved_discussions << discussion
      end
    end
  end

  def invite
    @invite_email = params[:email]
    @book_discussion.discussion_participants.push(@invite_email)
    UserMailer.invitation(@invite_email).deliver_now!
    if @book_discussion.save
      flash.now[:success] = "User has been invited!"
      render :show
    end
  end

  def all
    @book_discussions = BookDiscussion.where("status = ?", 'public')
  end

  def save
    current_user.saved_discussions.push(@book_discussion.id)
    current_user.save
    flash.now[:success] = 'Discussion saved. It will now show up under your saved discussions.'
    render :show
  end

  def remove_saved
    current_user.saved_discussions.delete(@book_discussion.id)
    current_user.save
    flash.now[:success] = 'Discussion removed from your saved discussions.'
    render :show
  end

  def search
    @books = FindBooks.new(params[:q]).call
    if @books == []
      flash.now[:error] = "Sorry, we couldn\'t find any books for that search."
      render :search
    elsif @books == [1]
      flash.now[:error] = "Goodreads is currently down, please try your search again later."
      render :search
    end
  end

  def search_discussions
    @book_discussions = BookDiscussion.where("lower(book_title) LIKE ? AND status = 'public'", "%#{params[:q].downcase}%")
    if @book_discussions == []
      flash.now[:error] = "Sorry, we couldn\'t find any public book discussions for that search."
    end
  end

  def create
    @book_discussion = current_user.book_discussions.new(book_params)
    @book_discussion[:status] = 'private'
    if @book_discussion.save
      redirect_to @book_discussion
    else
      render :search
    end
  end

  def change_status
    if @book_discussion.status == 'private'
      @book_discussion[:status] = 'public'
    else
      @book_discussion[:status] = 'private'
    end
    @book_discussion.save
    redirect_to @book_discussion
  end

  def show
    redirect_to '/404' unless @book_discussion
  end

  def destroy
    User.find_each do |user|
      user.saved_discussions.delete(@book_discussion.id)
      user.save
    end
    @book_discussion.destroy
    redirect_to '/book_discussions'
  end

  private

  def find_discussion
    @book_discussion = BookDiscussion.find_by(id: params[:id])
  end

  def book_params
    params.permit(:book_title, :book_author, :book_image_url)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user
      redirect_to '/book_discussions'
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      resource.errors.full_messages.each {|x| flash[x] = x}
      redirect_to '/users/sign_up'
    end
  end

  private

  def sign_up_params
   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_discussion, only: [:new, :create, :destroy]
  before_action :find_section, only: [:show, :destroy, :edit, :update]

  def new
    @section = Section.new
  end

  def create
    @section = @book_discussion.sections.new(section_params)
    if @section.save
      redirect_to @section.book_discussion
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @book_discussion = @section.book_discussion
    @section.destroy
    redirect_to @book_discussion
  end

  def edit
  end

  def update
    if @section.update_attributes(section_params)
      redirect_to @section
    else
      render :edit
    end
  end

  private

  def find_discussion
    @book_discussion = BookDiscussion.find_by(id: params[:book_discussion_id])
  end

  def find_section
    @section = Section.find_by(id: params[:id])
  end

  def section_params
    params.require(:section).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/book_discussions/_created_discussions.html.erb
<div class = "text-center center-block">
  <button data-toggle="collapse" data-target="#discussions-created" class="btn btn-info">View</button>

  <div id="discussions-created" class="collapse">
    <ul class="list-group">
      <% user_discussions.each do |discussion| %>
      <li class="list-group-item text-center" id="owned-discussions">
        <p class="bigger-links"><%= link_to discussion.book_title, discussion %></p>
        <p>By: <%= discussion.book_author %></p>
        <p><%= image_tag(discussion.book_image_url, :alt => "Cover Image") %></p>
      </li>
      <hr>
      <% end %>
    </ul>
  </div>

</div>

app/views/book_discussions/_disqus.html.erb
<h2 class="text-center">General Discussion</h2>

<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
  s.src = '//readtogether-1.disqus.com/embed.js';
          this.page.url = '<%= url_for(book_discussion) %>';
          this.page.identifier = '<%= book_discussion.id %>';
          this.page.title = '<%= book_discussion.book_title %><%= current_user.email %>';
};
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//readtogether-1.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/book_discussions/_invite_form.html.erb
<form action="/invite">
  <p>Enter the email address of the user you would like to invite to this discussion:</p>
  <div class="form-group">
    <input type="email" name="email" class="form-control" placeholder="Enter email">
  </div>
  <%= hidden_field_tag(:id, book_discussion.id) %>
  <button type="submit" class="btn btn-default">Invite</button>
</form>

app/views/book_discussions/_invited_discussions.html.erb
<div class = "text-center center-block">
  <button data-toggle="collapse" data-target="#discussions-invited" class="btn btn-info">View</button>

  <div id="discussions-invited" class="collapse">
    <ul class="list-group">
      <% book_discussions.each do |discussion| %>
        <li class="list-group-item text-center" id="invited-discussions">
          <p class="bigger-links"><%= link_to discussion.book_title, discussion %></p>
          <p>By: <%= discussion.book_author %></p>
          <p><%= image_tag(discussion.book_image_url, :alt => "Cover Image") %></p>
        </li>
        <hr>
      <% end %>
    </ul>
  </div>

</div>

app/views/book_discussions/_owner_options.html.erb
<div class="text-center">
  <div class="dropdown">
    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      Options
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <li><%= link_to 'Delete Discussion', book_discussion_path(book_discussion), method: :delete, data: {confirm: "Are you sure? This will delete all sections and comments for this discussion as well."} %></li>
      <li><%= link_to 'Create Section', new_section_path(book_discussion_id: book_discussion.id) %></li>
      <% if book_discussion.status == 'public' %>
        <li><%= link_to 'Make Private', status_path(id: book_discussion.id) %></li>
      <% else %>
        <li><%= link_to 'Make Public', status_path(id: book_discussion.id) %></li>
      <% end %>
    </ul>
  </div>
</div>

<div id="invite-container" class="center-block text-center">
  <button data-toggle="collapse" data-target="#invite" class="btn btn-info">Invite User</button>

  <div id="invite" class="collapse">
    <br>
    <%= render 'invite_form', { book_discussion: book_discussion } %>
  </div>
</div>

<div class="text-center" id="discussion-status-container">
  <% if book_discussion.status == 'public' %>
    <p>This discussion is currently <strong>public</strong>, which means any users can see this discussion and comment on discussion sections you create. You can change this under options.</p>
  <% else %>
    <p>This discussion is currently <strong>private</strong>, which means only users you invite can see this discussion and comment on discussion sections you create. You can change this under options.</p>
  <% end %>
</div>

app/views/book_discussions/_save_discussion.html.erb
<div class="text-right" id="save-discussion">
  <% if current_user.saved_discussions.include?(book_discussion.id) %>
    <%= link_to 'Remove from Saved', remove_saved_path(id: book_discussion.id) %>
  <% else %>
    <%= link_to 'Save Discussion', save_path(id: book_discussion.id) %>
  <% end %>
</div>

app/views/book_discussions/_saved_discussions.html.erb
<div class = "text-center center-block">
  <button data-toggle="collapse" data-target="#discussions-saved" class="btn btn-info">View</button>

  <div id="discussions-saved" class="collapse">
    <ul class="list-group">
      <% saved_discussions.each do |discussion| %>
      <li class="list-group-item text-center" id="saved-discussions">
        <p class="bigger-links"><%= link_to discussion.book_title, discussion %></p>
        <p>By: <%= discussion.book_author %></p>
        <p><%= image_tag(discussion.book_image_url, :alt => "Cover Image") %></p>
      </li>
      <% end %>
    </ul>
  </div>

</div>

app/views/book_discussions/_search_public.html.erb
<form class="center-block" id="search-discussions-form" role="search" action="/search_discussions">
  <div class="form-group">
    <input type="text" name="q" class="form-control" placeholder="Search Public Discussions...">
  </div>
  <button type="submit" class="btn btn-default">Search</button>
</form>

app/views/book_discussions/_section.html.erb
<% if book_discussion.sections == [] && book_discussion.user_id != current_user.id %>
  <p class="text-center">The owner of this discussion has not created any discussion sections yet.</p>
<% elsif book_discussion.sections == [] && book_discussion.user_id == current_user.id %>
  <p class="text-center">You have not created any discussion sections for this book yet. Select "Create Section" under options to get started.</p>
<% else %>
  <h2 class="text-center">Discussion Sections</h2>
  <div class="text-center">
    <button data-toggle="collapse" data-target="#discussion-sections" class="btn btn-info">View</button>

    <div id="discussion-sections" class="collapse">
      <ul class="list-group text-center">
        <% book_discussion.sections.all.each do |section| %>
          <li class=list-group-item><%= link_to section.title, section %></li>
          <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/book_discussions/all.html.erb
<h1 class="text-center header-style">All Public Discussions</h1>

<hr class="discussion-divider">

<% if @book_discussions == [] %>
  <p class="text-center">No public discussions exist. You can create your own private discussion and invite your friends or set it to public to allow anyone to participate. <br> To create a discussion first search for a book you would like to discuss.</p>
<% else %>
  <ul class="list-group">
    <% @book_discussions.each do |discussion| %>
    <li class="list-group-item text-center" id="invited-discussions">
      <p class="bigger-links"><%= link_to discussion.book_title, discussion %></p>
      <p>By: <%= discussion.book_author %></p>
      <p><%= image_tag(discussion.book_image_url, :alt => "Cover Image") %></p>
    </li>
    <hr>
    <% end %>
  </ul>
<% end %>

app/views/book_discussions/index.html.erb
<% if current_user %>
  <h1 class="text-center header-style">Discussions You've Created</h1>

  <hr class="discussion-divider">

  <% if current_user.book_discussions.any? %>
    <%= render 'created_discussions', { user_discussions: current_user.book_discussions } %>
  <% else %>
    <p class="text-center">You haven't created any discussions yet. Search for a book to get started.</p>
  <% end %>

  <h1 class="text-center header-style">Discussions You're Invited To</h1>

  <hr class="discussion-divider">

  <% if @book_discussions != [] %>
    <%= render 'invited_discussions', { book_discussions: @book_discussions } %>
  <% else %>
    <p class="text-center">You haven't been invited to any discussions yet.</p>
  <% end %>

  <h1 class="text-center header-style">Discussions You've Saved</h1>

  <hr class="discussion-divider">

  <% if current_user.saved_discussions != [] %>
    <%= render 'saved_discussions', { saved_discussions: @saved_discussions } %>
  <% else %>
    <p class="text-center">You have not saved any discussions yet. Only public discussions can be saved. Private discussions that you can participate in will automatically appear under "Discussions You're Invited To".</p>
  <% end %>
<% end %>

app/views/book_discussions/search.html.erb
<h1 class="text-center header-style">Search Results</h1>

<hr class="discussion-divider">

<% @books.each do |book| %>
  <hr>
    <div class="row">
      <div class="col-xs-12 col-sm-2 text-center">
        <%= image_tag(book[2], :alt => "Cover Image") %>
      </div>
      <div class="col-xs-12 col-sm-10" id="book-search-info">
        <p><%= book[0] %></p>
        <p>By: <%= book[1] %></p>
        <%= link_to 'Create Discussion', book_discussions_path(book_title: book[0], book_image_url: book[2], book_author: book[1]), method: :post, class: 'bigger-links' %>
      </div>
    </div>
  <hr>
<% end %>

app/views/book_discussions/search_discussions.html.erb
<h1 class="text-center header-style">Search Results</h1>

<%= render 'search_public' %>

<ul class="list-group">
  <% @book_discussions.each do |discussion| %>
  <li class="list-group-item text-center" id="invited-discussions">
    <p class="bigger-links"><%= link_to discussion.book_title, discussion %></p>
    <p>By: <%= discussion.book_author %></p>
    <p><%= image_tag(discussion.book_image_url, :alt => "Cover Image") %></p>
  </li>
  <hr>
  <% end %>
</ul>

app/views/book_discussions/show.html.erb
<% if current_user.id == @book_discussion.user_id || @book_discussion.discussion_participants.include?(current_user.email) || @book_discussion.status == 'public' %>

  <% if @book_discussion.status == 'public' %>
    <%= render 'save_discussion', book_discussion: @book_discussion %>
  <% end %>

  <h1 class="text-center header-style"><%= @book_discussion.book_title %></h1>
  <p class="text-center">By: <%= @book_discussion.book_author %></p>
  <p class="text-center"><%= image_tag(@book_discussion.book_image_url, :alt => "Cover Image") %></p>


  <% if current_user.id == @book_discussion.user_id %>
    <%= render 'owner_options', { book_discussion: @book_discussion } %>
  <% end %>

  <hr class="discussion-divider">

  <div id="sections-container" class="center-block">
    <%= render 'section', { book_discussion: @book_discussion } %>
  </div>

  <hr class="discussion-divider">

  <div class="disqus-container center-block">
    <%= render 'disqus', { book_discussion: @book_discussion } %>
  </div>

<% else %>
  <h1 class="text-center header-style">Sorry, you're not permitted to view this discussion.</h1>
<% end %>

app/views/home/index.html.erb
<body id="book-background">
  <div class="jumbotron center-block">
    <h1 class="text-center header-style">Welcome!</h1>
    <h2 class="text-left header-style">What is Read Together?</h2>
    <p class="text-left">Read together is an easy way for you to discuss your favorite books with other people. Once you log in, you'll be directed to your discussions page which shows the discussions you've created, as well as those you've been invited to. To get started with creating your own discussion, simply search for a book. Discussions are private by default, meaning only users you invite to the discussion can comment, but you can also make your discussions public, allowing any user to see and comment on your discussions.</p>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Read Together</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <% if current_user %>
            <a class="navbar-brand" href="/book_discussions">Read Together</a>
          <% else %>
            <a class="navbar-brand" href="/">Read Together</a>
          <% end %>
        </div>

        <% if current_user %>
          <form class="navbar-form navbar-left" role="search" action="/search">
            <div class="form-group">
              <input type="text" name="q" class="form-control" placeholder="Find Book...">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form>
        <% end %>

        <ul class='nav navbar-nav navbar-right'>
          <% if current_user %>
          <li id="greeting">Hello, <%= current_user.first_name %>!</li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'Register', new_user_registration_path %></li>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info text-center" %>
    <% end %>

    <% if current_user %>
      <p class="text-right" id="all-discussions"><%= link_to 'See Public Discussions', all_path %></p>
    <% end %>

    <%= yield %>

    <% if current_user %>
      <footer>
        <hr>
        <p class="text-right">All book data is provided by <a href="https://www.goodreads.com/">GoodReads</a>.</p>
      </footer>
    <% end %>
  </body>
</html>

app/views/sections/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
  s.src = '//readtogether-1.disqus.com/embed.js';
          this.page.url = '<%= url_for(section) %>';
          this.page.identifier = '<%= section.id %>';
          this.page.title = '<%= section.title %><%= current_user.email %>';
};
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//readtogether-1.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/sections/_form.html.erb
<%= form_for (section) do |f| %>

  <p class="text-center">A section is a specific topic related to the book you would like to discuss (ex: chapters, specific characters, memorable moments, etc...)</p>

  <div class="text-center">
    <div class="field input">
      <%= f.label :title %>
      <%= f.text_field :title, required: 'required' %>
    </div>


    <div class="actions input">
      <%= hidden_field_tag(:book_discussion_id, book_discussion.id) %>
      <%= f.submit "Create Section", class: "btn btn-success" %>
    </div>
  </div>

<% end %>

app/views/sections/_options.html.erb
<div class="text-center">
  <div class="dropdown">
    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      Options
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <li><%= link_to 'Delete Section', section_path(section), method: :delete, data: {confirm: "Are you sure? This will delete all comments for this section as well."} %></li>
      <li><%= link_to 'Edit Section', edit_section_path(section) %></li>
    </ul>
  </div>
</div>

app/views/sections/_owner_options.html.erb
<div class="text-center">
  <div class="dropdown">
    <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      Options
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <li><%= link_to 'Delete Section', section_path(section), method: :delete, data: {confirm: "Are you sure? This will delete all comments for this section as well."} %></li>
      <li><%= link_to 'Edit Section', edit_section_path(section) %></li>
    </ul>
  </div>
</div>

app/views/sections/edit.html.erb
<h1 class="text-center"><%= @section.title %></h1>

<%= form_for (@section) do |f| %>

  <div class="text-center">
    <div class="field input">
      <%= f.label :title %>
      <%= f.text_field :title, required: 'required' %>
    </div>

    <div class="actions input">
      <%= f.submit %>
    </div>
  </div>

<% end %>

app/views/sections/new.html.erb
<h1 class="text-center header-style">Create a Section for: <%= @book_discussion.book_title %></h1>

<%= render 'form', { section: @section, book_discussion: @book_discussion } %>

app/views/sections/show.html.erb
<h1 class="text-center header-style"><%= @section.title %></h1>
<h2 class="text-center"><%= link_to @section.book_discussion.book_title, @section.book_discussion %></h2>
<p class="text-center">By: <%= @section.book_discussion.book_author %></p>
<p class="text-center"><%= image_tag(@section.book_discussion.book_image_url, :alt => "Cover Image") %></p>

<% if @section.book_discussion.user_id == current_user.id %>
  <%= render 'owner_options', { section: @section } %>
<% end %>

<hr class="discussion-divider">

<div class="disqus-container center-block">
  <%= render 'disqus', { section: @section } %>
</div>